### list topic
GET http://localhost:8080/topics

### send message to the topic
POST http://localhost:8080/topics/event
Content-Type: application/vnd.kafka.json.v2+json

{
   "records": [
      {
         "key": "event3",
         "value": "1"
      },
      {
         "key": "event4",
         "value": "2"
      }
   ]
}


#### register a kafka consumer in a new consumer group
POST http://localhost:8080/consumers/strimzi-kafka-consumer-group
Content-Type: application/vnd.kafka.v2+json

{
   "name": "strimzi-kafka-consumer",
   "auto.offset.reset": "earliest",
   "format": "json",
   "enable.auto.commit": true,
   "fetch.min.bytes": 512,
   "consumer.request.timeout.ms": 30000
}

### Delete the consumer
DELETE http://localhost:8080/consumers/strimzi-kafka-consumer-group/instances/strimzi-kafka-consumer


### subscribe to the topic
POST http://localhost:8080/consumers/strimzi-kafka-consumer-group/instances/strimzi-kafka-consumer/subscription
Content-Type: application/vnd.kafka.v2+json

{
   "topics": ["event"]
}


### consume message with the consumer
GET http://localhost:8080/consumers/strimzi-kafka-consumer-group/instances/strimzi-kafka-consumer/records
Content-Type: application/json
accept: application/vnd.kafka.json.v2+json